#!/usr/bin/env bash
# display the content of the current directory in a list format
# where only the part of the name after the first dash is displayed e.g. 8-for_ls -> for_ls.
# do not display hidden files
for file in *; do
    echo "$file" | cut -d '-' -f 2 # split the string by the delimiter '-' and print the second field
done
